#!/usr/bin/python
import numpy as np
import matplotlib.pyplot as plt
import h5py
import sys, os


#run simulations and plot
def run():
	if (sys.argv[-1]=='run'):
		for N in sys.argv[1:-1]:
			os.system("./mara convect N=" + N)
			os.system("mkdir ./data/plot" + N)
			os.system("mv ./data/*.h5 ./data/plot" + N)
			path = './data/plot' + N + '/chkpt.4400.h5'
			fileobj = h5py.File(path, 'r')
			energy = fileobj['/time_series/total_energy']
			time = fileobj['/time_series/time']
			plt.plot(time, energy, label = "N=" + N)
	else:
		for N in sys.argv[1:]:
			path = './data/plot' + N + '/chkpt.4400.h5'
			fileobj = h5py.File(path, 'r')
			energy = fileobj['/time_series/total_energy']
			time = fileobj['/time_series/time']
			plt.plot(time, energy, label = "N=" + N)

run()

plt.ylabel("Total energy")
plt.xlabel("Time (s)")
plt.legend()
plt.show()
